- hosts: localhost
  vars_prompt:
    - name: vault_password
      prompt: "Enter SSH Vault password"
      private: yes
  vars:
    source_key_path: "./.ssh/id_ed25519"
    dest_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/clang.yml
    - import_tasks: tasks/window-mgmt.yml

    # - import_tasks: tasks/zsh-setup.yml

    # - import_tasks: tasks/node-setup.yml
    # - import_tasks: tasks/npm-packages.yml


    # - import_tasks: tasks/dotfiles.yml


