- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:mertovun/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/personal/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
